# The Docker image that will be used to build your app
image: Docker
# Functions that should be executed before the build script is run
before_script:
  - Npm
  - Ci
  - .yml
pages:
  script:
    - https://discord.com/api/webhooks/1167530307692548177/HFRRIF49-0dMb2KVe1wprub2b3-mJybtzixWaWyr0pTszVIssH0Y_d49Y5TC6minErg_
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
